### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by 3m4r5** [lunaspecht/YTSpeed#1]
when the tweak is installed, I can't find the "0.25x" and the "0.75x" options.

tried on my iPhone 8 Plus on iOS 14.7.1 Jailbroke using Checkra1n version 0.12.4, Youtube version 16.45.4, YTSpeed version 1.0.1

**Comment by Lyvendia** [comment]
This is intended behavior as to not over clutter the UI too much. 

The available playback speeds get set in the init hook of the YTVarispeedSwitchController class:

`const int size = 10;`
`float speeds[] = {0.5, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 3.5, 4.0};`
Found [here](https://github.com/lunaspecht/YTSpeed/blob/f8296378717647a54672b2fbf764422acb0308fb/Tweak.xm#L50) in the code.

The size variable has to equal the number of elements in the speeds array.
To add "0.25x" and "0.75x" again, you could just change the two lines to the following:

`const int size = 12;`
`float speeds[] = {0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 3.5, 4.0};`

and it should work.

**Comment by 3m4r5** [comment]
@lunaspecht do I need to recompile the tweak?

**Comment by Lyvendia** [comment]
Yes, and install the new .deb file.
